name: transcribe_lectures
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - plotly>=5.15.0
  - opencv>=4.8.0
  - ffmpeg
  - pip:
    - openai-whisper>=20231117
    - ffmpeg-python>=0.2.0
    - librosa>=0.10.0
    - soundfile>=0.12.0
    - torch>=2.0.0
    - torchaudio>=2.0.0
    - jupyter>=1.0.0
    - ipykernel>=6.25.0 